/**
 * PrivacyPage.jsx
 * Standardized Privacy Policy document for VerifyChain.
 */
import { useReveal } from '../animations/useReveal';
import { Container } from '../layouts/Container';

export function PrivacyPage() {
  const revealRef = useReveal();

  return (
    <div ref={revealRef} className="py-12 lg:py-16">
      <Container size="md">
        <div className="mb-8 pb-6 border-b border-[--vc-border]">
          <span className="text-[--text-xs] font-semibold uppercase tracking-[--ls-caps] text-[--vc-text-tertiary] block mb-2">
            Legal Compliance Document
          </span>
          <h1 className="font-[--font-heading] text-[--text-3xl] font-bold text-[--vc-text-primary] mb-2">
            Privacy Policy
          </h1>
          <p className="text-[--text-xs] text-[--vc-text-tertiary]">
            Last Updated: July 2026 • Status: Draft (Pending Final Counsel Review)
          </p>
        </div>

        <div className="prose max-w-none text-[--text-sm] text-[--vc-text-secondary] leading-[--lh-relaxed] flex flex-col gap-6">
          <section>
            <h3 className="font-[--font-heading] text-[--text-base] font-semibold text-[--vc-text-primary] mb-2">
              1. Information We Collect
            </h3>
            <p>
              VerifyChain processes business identifier data (including GSTIN, Udyam Registration Number, company registration details, and employee counts) to aggregate public compliance standing across government regulatory databases.
            </p>
          </section>

          <section>
            <h3 className="font-[--font-heading] text-[--text-base] font-semibold text-[--vc-text-primary] mb-2">
              2. How Information is Used
            </h3>
            <p>
              Processed business data is utilized strictly to compute the Compliance Health Score (CHS), display verified public supplier cards, trigger expiration notification alerts, and match enterprises to eligible government subsidy programs.
            </p>
          </section>

          <section>
            <h3 className="font-[--font-heading] text-[--text-base] font-semibold text-[--vc-text-primary] mb-2">
              3. Data Security & Integrity
            </h3>
            <p>
              All stored document metadata and compliance records are encrypted at rest using industry-standard protocols. Scores are calculated deterministically on-demand and are never sold or shared with unverified third-party advertisers.
            </p>
          </section>

          <section>
            <h3 className="font-[--font-heading] text-[--text-base] font-semibold text-[--vc-text-primary] mb-2">
              4. Zero-Auth Public Verification
            </h3>
            <p>
              Verified Supplier Cards generated by business owners contain public-facing regulatory status summaries intended for procurement officers. Business owners maintain full control over sharing their public profile URL.
            </p>
          </section>
        </div>
      </Container>
    </div>
  );
}
