/**
 * builtinProviders.js
 * Production Built-in Provider Registry Definitions for VerifyChain.
 * Ships out-of-the-box with platform capabilities across ERP, CRM, Accounting, Identity,
 * Communication, Generic API, and Government categories.
 */

const BUILTIN_PROVIDERS = Object.freeze([
  // ─── ERP CONNECTORS ───────────────────────────────────────────────
  {
    providerCode: 'SAP_ERP',
    name: 'SAP S/4HANA Enterprise ERP',
    category: 'ERP',
    type: 'ERP',
    description: 'Enterprise resource planning adapter for financial ledgers, vendor master data, procurement orders, and statutory compliance audit.',
    logo: 'Sap',
    version: 'v2.4.0',
    status: 'ACTIVE',
    supportedAuthMethods: ['MUTUAL_TLS', 'OAUTH2', 'BASIC_AUTH'],
    capabilities: ['FINANCIAL_SYNC', 'VENDOR_VERIFICATION', 'PURCHASE_ORDER_AUDIT', 'REALTIME_HEALTH'],
    supportedResources: ['Vendors', 'PurchaseOrders', 'Invoices', 'Ledgers', 'TaxDetails'],
    docUrl: 'https://docs.verifychain.io/connectors/sap-s4hana',
    healthSupport: true,
    webhookSupport: true,
    syncSupport: { enabled: true, modes: ['FULL', 'INCREMENTAL', 'REAL_TIME'] },
    featureFlags: { autoDiscovery: true, hmacVerification: true, rateLimitThrottling: true, dataMapping: true },
    configSchema: {
      type: 'object',
      required: ['baseUrl', 'clientLanguage', 'systemNumber'],
      properties: {
        baseUrl: { type: 'string', title: 'SAP Endpoint Base URL', placeholder: 'https://sap-s4.enterprise.internal:8000' },
        clientLanguage: { type: 'string', title: 'Client ID / Language', default: '100 / EN' },
        systemNumber: { type: 'string', title: 'System Number (Instance)', default: '00' },
        apiKey: { type: 'string', title: 'API Key / Secret Token', secret: true },
      },
    },
    extensibility: { customFieldsSupported: true, extensionHooks: ['PRE_SYNC', 'POST_SYNC', 'MAPPING_TRANSFORM'] },
  },
  {
    providerCode: 'ORACLE_ERP',
    name: 'Oracle Fusion Cloud ERP',
    category: 'ERP',
    type: 'ERP',
    description: 'Oracle Cloud ERP connector for automated accounts payable, supplier onboarding, risk telemetry, and audit trail synchronization.',
    logo: 'Oracle',
    version: 'v1.8.2',
    status: 'ACTIVE',
    supportedAuthMethods: ['OAUTH2', 'MUTUAL_TLS'],
    capabilities: ['SUPPLIER_RISK_AUDIT', 'INVOICE_MATCHING', 'PAYABLE_SYNC'],
    supportedResources: ['Suppliers', 'Payables', 'Contracts', 'RiskScores'],
    docUrl: 'https://docs.verifychain.io/connectors/oracle-fusion',
    healthSupport: true,
    webhookSupport: true,
    syncSupport: { enabled: true, modes: ['FULL', 'INCREMENTAL'] },
    featureFlags: { autoDiscovery: true, rateLimitThrottling: true, dataMapping: true },
    configSchema: {
      type: 'object',
      required: ['baseUrl', 'identityDomain'],
      properties: {
        baseUrl: { type: 'string', title: 'Oracle Cloud ERP Endpoint', placeholder: 'https://fa-instance.oraclecloud.com' },
        identityDomain: { type: 'string', title: 'Identity Domain / Tenant', placeholder: 'idcs-123456789' },
        apiKey: { type: 'string', title: 'OAuth2 Client Secret', secret: true },
      },
    },
    extensibility: { customFieldsSupported: true, extensionHooks: ['POST_SYNC'] },
  },
  {
    providerCode: 'MS_DYNAMICS_365',
    name: 'Microsoft Dynamics 365 Business Central',
    category: 'ERP',
    type: 'ERP',
    description: 'Mid-market & enterprise ERP integration for Business Central financial ledgers, tax verification, and inventory sync.',
    logo: 'Dynamics',
    version: 'v3.1.0',
    status: 'ACTIVE',
    supportedAuthMethods: ['OAUTH2', 'BEARER_TOKEN'],
    capabilities: ['GST_INVOICE_SYNC', 'VENDOR_PROFILE_AUDIT', 'OFFLINE_RECOVERY'],
    supportedResources: ['Vendors', 'PurchaseInvoices', 'GLAccounts', 'TaxRegistrations'],
    docUrl: 'https://docs.verifychain.io/connectors/dynamics365',
    healthSupport: true,
    webhookSupport: true,
    syncSupport: { enabled: true, modes: ['FULL', 'INCREMENTAL', 'REAL_TIME'] },
    featureFlags: { autoDiscovery: true, hmacVerification: true, dataMapping: true },
    configSchema: {
      type: 'object',
      required: ['tenantId', 'environmentName', 'companyId'],
      properties: {
        tenantId: { type: 'string', title: 'Azure AD Tenant ID', placeholder: '00000000-0000-0000-0000-000000000000' },
        environmentName: { type: 'string', title: 'Environment Name', default: 'Production' },
        companyId: { type: 'string', title: 'Business Central Company ID', placeholder: 'CRONUS International' },
        apiKey: { type: 'string', title: 'Client Secret Key', secret: true },
      },
    },
    extensibility: { customFieldsSupported: true, extensionHooks: ['MAPPING_TRANSFORM'] },
  },

  // ─── CRM CONNECTORS ───────────────────────────────────────────────
  {
    providerCode: 'SALESFORCE_CRM',
    name: 'Salesforce Enterprise CRM',
    category: 'CRM',
    type: 'CRM',
    description: 'Bi-directional CRM adapter for customer directory, account trust enrichment, buyer deal verification, and webhook push.',
    logo: 'Salesforce',
    version: 'v2.1.0',
    status: 'ACTIVE',
    supportedAuthMethods: ['OAUTH2', 'JWT_BEARER'],
    capabilities: ['SUPPLIER_TRUST_ENRICHMENT', 'BUYER_DIRECTORY_SYNC', 'REALTIME_WEBHOOK_PUSH'],
    supportedResources: ['Accounts', 'Contacts', 'Opportunities', 'SupplierProfiles'],
    docUrl: 'https://docs.verifychain.io/connectors/salesforce',
    healthSupport: true,
    webhookSupport: true,
    syncSupport: { enabled: true, modes: ['FULL', 'INCREMENTAL', 'REAL_TIME'] },
    featureFlags: { autoDiscovery: true, hmacVerification: true, rateLimitThrottling: true, lightningWidget: true },
    configSchema: {
      type: 'object',
      required: ['instanceUrl', 'clientId'],
      properties: {
        instanceUrl: { type: 'string', title: 'Salesforce Instance URL', placeholder: 'https://yourinstance.my.salesforce.com' },
        clientId: { type: 'string', title: 'Connected App Consumer Key', placeholder: '3MVG9...' },
        apiKey: { type: 'string', title: 'Consumer Secret / Private Key', secret: true },
      },
    },
    extensibility: { customFieldsSupported: true, extensionHooks: ['PRE_SYNC', 'POST_SYNC', 'CUSTOM_SOQL'] },
  },
  {
    providerCode: 'HUBSPOT_CRM',
    name: 'HubSpot CRM & Sales Hub',
    category: 'CRM',
    type: 'CRM',
    description: 'Inbound growth & sales CRM integration to verify MSME business profiles, sync deal stages, and auto-enrich contact data.',
    logo: 'Hubspot',
    version: 'v1.5.0',
    status: 'ACTIVE',
    supportedAuthMethods: ['OAUTH2', 'BEARER_TOKEN'],
    capabilities: ['DEAL_VERIFICATION_SYNC', 'CONTACT_ENRICHMENT', 'AUTOMATED_ALERTS'],
    supportedResources: ['Companies', 'Contacts', 'Deals', 'LineItems'],
    docUrl: 'https://docs.verifychain.io/connectors/hubspot',
    healthSupport: true,
    webhookSupport: true,
    syncSupport: { enabled: true, modes: ['FULL', 'INCREMENTAL'] },
    featureFlags: { autoDiscovery: true, rateLimitThrottling: true },
    configSchema: {
      type: 'object',
      required: ['portalId'],
      properties: {
        portalId: { type: 'string', title: 'HubSpot Hub / Portal ID', placeholder: '12345678' },
        apiKey: { type: 'string', title: 'Private App Access Token', secret: true },
      },
    },
    extensibility: { customFieldsSupported: true, extensionHooks: ['MAPPING_TRANSFORM'] },
  },
  {
    providerCode: 'ZOHO_CRM',
    name: 'Zoho CRM Suite',
    category: 'CRM',
    type: 'CRM',
    description: 'Zoho Suite CRM connector for MSME lead pipeline verification, statutory tax matching, and automated account updates.',
    logo: 'Zoho',
    version: 'v1.4.1',
    status: 'ACTIVE',
    supportedAuthMethods: ['OAUTH2'],
    capabilities: ['LEAD_VERIFICATION_SYNC', 'ACCOUNT_TAX_MATCH', 'SYNC_AUDIT'],
    supportedResources: ['Leads', 'Accounts', 'Vendors', 'PurchaseOrders'],
    docUrl: 'https://docs.verifychain.io/connectors/zoho-crm',
    healthSupport: true,
    webhookSupport: true,
    syncSupport: { enabled: true, modes: ['FULL', 'INCREMENTAL'] },
    featureFlags: { autoDiscovery: true, rateLimitThrottling: true },
    configSchema: {
      type: 'object',
      required: ['dcLocation', 'clientId'],
      properties: {
        dcLocation: { type: 'string', title: 'Data Center Location', default: 'com (US)' },
        clientId: { type: 'string', title: 'Zoho Client ID', placeholder: '1000.XXXXX' },
        apiKey: { type: 'string', title: 'Zoho Client Secret Key', secret: true },
      },
    },
    extensibility: { customFieldsSupported: true, extensionHooks: ['POST_SYNC'] },
  },

  // ─── ACCOUNTING CONNECTORS ─────────────────────────────────────────
  {
    providerCode: 'QUICKBOOKS',
    name: 'QuickBooks Online Enterprise',
    category: 'ACCOUNTING',
    type: 'CUSTOM',
    description: 'Cloud accounting bridge for invoice verification, GST reconciliation, accounts payable, and ledger synchronization.',
    logo: 'QuickBooks',
    version: 'v2.0.1',
    status: 'ACTIVE',
    supportedAuthMethods: ['OAUTH2'],
    capabilities: ['INVOICE_SYNC', 'GST_RECONCILIATION', 'PAYABLE_AUDIT'],
    supportedResources: ['Invoices', 'Bills', 'Vendors', 'TaxRates'],
    docUrl: 'https://docs.verifychain.io/connectors/quickbooks',
    healthSupport: true,
    webhookSupport: true,
    syncSupport: { enabled: true, modes: ['FULL', 'INCREMENTAL', 'REAL_TIME'] },
    featureFlags: { autoDiscovery: true, hmacVerification: true, rateLimitThrottling: true },
    configSchema: {
      type: 'object',
      required: ['realmId'],
      properties: {
        realmId: { type: 'string', title: 'QuickBooks Company / Realm ID', placeholder: '1234567890' },
        apiKey: { type: 'string', title: 'OAuth Access / Refresh Token', secret: true },
      },
    },
    extensibility: { customFieldsSupported: true, extensionHooks: ['MAPPING_TRANSFORM'] },
  },
  {
    providerCode: 'TALLY_PRIME',
    name: 'TallyPrime Enterprise Bridge',
    category: 'ACCOUNTING',
    type: 'ERP',
    description: 'On-premise & desktop MSME accounting connector for Tally XML/ODBC sync, GST invoice verification, and local bridge support.',
    logo: 'Tally',
    version: 'v3.0.0',
    status: 'ACTIVE',
    supportedAuthMethods: ['LOCAL_BRIDGE_KEY', 'BASIC_AUTH'],
    capabilities: ['GST_INVOICE_SYNC', 'TAX_FILING_AUDIT', 'OFFLINE_SYNC_ENGINE'],
    supportedResources: ['LedgerMasters', 'Vouchers', 'GSTInvoices', 'DayBook'],
    docUrl: 'https://docs.verifychain.io/connectors/tally-prime',
    healthSupport: true,
    webhookSupport: false,
    syncSupport: { enabled: true, modes: ['FULL', 'INCREMENTAL', 'MANUAL'] },
    featureFlags: { autoDiscovery: false, localBridge: true, offlineSync: true },
    configSchema: {
      type: 'object',
      required: ['bridgePort', 'companyName'],
      properties: {
        bridgePort: { type: 'string', title: 'Tally ODBC / XML Port', default: '9000' },
        companyName: { type: 'string', title: 'Tally Active Company Name', placeholder: 'Apex Precision Tools Pvt Ltd' },
        apiKey: { type: 'string', title: 'Tally Local Agent Security Token', secret: true },
      },
    },
    extensibility: { customFieldsSupported: true, extensionHooks: ['PRE_SYNC', 'POST_SYNC'] },
  },
  {
    providerCode: 'XERO',
    name: 'Xero Cloud Accounting',
    category: 'ACCOUNTING',
    type: 'CUSTOM',
    description: 'Global cloud accounting adapter for vendor bills, statutory compliance reconciliation, and automated payment status sync.',
    logo: 'Xero',
    version: 'v1.7.0',
    status: 'ACTIVE',
    supportedAuthMethods: ['OAUTH2'],
    capabilities: ['BILL_PAYMENT_SYNC', 'VENDOR_COMPLIANCE_CHECK', 'BANK_RECONCILIATION'],
    supportedResources: ['Invoices', 'Contacts', 'BankTransactions', 'TaxRates'],
    docUrl: 'https://docs.verifychain.io/connectors/xero',
    healthSupport: true,
    webhookSupport: true,
    syncSupport: { enabled: true, modes: ['FULL', 'INCREMENTAL'] },
    featureFlags: { autoDiscovery: true, rateLimitThrottling: true },
    configSchema: {
      type: 'object',
      required: ['tenantId'],
      properties: {
        tenantId: { type: 'string', title: 'Xero Connected Tenant ID', placeholder: '00000000-0000-0000-0000-000000000000' },
        apiKey: { type: 'string', title: 'OAuth2 Refresh Token', secret: true },
      },
    },
    extensibility: { customFieldsSupported: true, extensionHooks: ['MAPPING_TRANSFORM'] },
  },

  // ─── IDENTITY CONNECTORS ──────────────────────────────────────────
  {
    providerCode: 'ENTRA_ID',
    name: 'Microsoft Entra ID (Azure AD)',
    category: 'IDENTITY',
    type: 'OAUTH',
    description: 'Enterprise SSO, SCIM user provisioning, role-based access enforcement, and tenant token validation.',
    logo: 'Entra',
    version: 'v2.2.0',
    status: 'ACTIVE',
    supportedAuthMethods: ['OAUTH2', 'OPENID_CONNECT'],
    capabilities: ['ENTERPRISE_SSO', 'SCIM_PROVISIONING', 'MFA_AUDIT_LOGGING'],
    supportedResources: ['Users', 'Groups', 'DirectoryRoles', 'AuditLogs'],
    docUrl: 'https://docs.verifychain.io/connectors/entra-id',
    healthSupport: true,
    webhookSupport: true,
    syncSupport: { enabled: true, modes: ['FULL', 'REAL_TIME'] },
    featureFlags: { autoDiscovery: true, scimSupport: true, ssoEnforcement: true },
    configSchema: {
      type: 'object',
      required: ['tenantId', 'clientId'],
      properties: {
        tenantId: { type: 'string', title: 'Microsoft Entra Tenant ID', placeholder: '00000000-0000-0000-0000-000000000000' },
        clientId: { type: 'string', title: 'Application (Client) ID', placeholder: '00000000-0000-0000-0000-000000000000' },
        apiKey: { type: 'string', title: 'Client Secret Value', secret: true },
      },
    },
    extensibility: { customFieldsSupported: true, extensionHooks: ['PRE_AUTH', 'POST_AUTH'] },
  },
  {
    providerCode: 'OKTA',
    name: 'Okta Identity Cloud',
    category: 'IDENTITY',
    type: 'OAUTH',
    description: 'Workforce identity verification, multi-factor security audit, OAuth authorization policies, and continuous session monitoring.',
    logo: 'Okta',
    version: 'v2.0.0',
    status: 'ACTIVE',
    supportedAuthMethods: ['OAUTH2', 'OPENID_CONNECT', 'API_KEY'],
    capabilities: ['WORKFORCE_IDENTITY', 'SYSTEM_AUDIT_STREAM', 'SECURITY_POLICY_ENFORCEMENT'],
    supportedResources: ['Users', 'AppGrants', 'SecurityEvents', 'GroupRules'],
    docUrl: 'https://docs.verifychain.io/connectors/okta',
    healthSupport: true,
    webhookSupport: true,
    syncSupport: { enabled: true, modes: ['FULL', 'REAL_TIME'] },
    featureFlags: { autoDiscovery: true, rateLimitThrottling: true, hmacVerification: true },
    configSchema: {
      type: 'object',
      required: ['domain'],
      properties: {
        domain: { type: 'string', title: 'Okta Domain URL', placeholder: 'https://your-org.okta.com' },
        apiKey: { type: 'string', title: 'Okta SSWS API Token', secret: true },
      },
    },
    extensibility: { customFieldsSupported: true, extensionHooks: ['PRE_AUTH', 'POST_AUTH'] },
  },
  {
    providerCode: 'AUTH0',
    name: 'Auth0 Universal Identity',
    category: 'IDENTITY',
    type: 'OAUTH',
    description: 'Universal customer & partner authentication adapter for OpenID Connect, JWT validation, and RBAC token exchange.',
    logo: 'Auth0',
    version: 'v1.6.0',
    status: 'ACTIVE',
    supportedAuthMethods: ['OAUTH2', 'OPENID_CONNECT', 'BEARER_TOKEN'],
    capabilities: ['JWT_VERIFICATION', 'USER_MANAGEMENT_SYNC', 'CUSTOM_DOMAIN_AUTH'],
    supportedResources: ['Users', 'Roles', 'Connections', 'Logs'],
    docUrl: 'https://docs.verifychain.io/connectors/auth0',
    healthSupport: true,
    webhookSupport: true,
    syncSupport: { enabled: true, modes: ['FULL', 'REAL_TIME'] },
    featureFlags: { autoDiscovery: true, hmacVerification: true },
    configSchema: {
      type: 'object',
      required: ['domain', 'clientId'],
      properties: {
        domain: { type: 'string', title: 'Auth0 Domain', placeholder: 'your-tenant.auth0.com' },
        clientId: { type: 'string', title: 'Management API Client ID', placeholder: 'Client ID' },
        apiKey: { type: 'string', title: 'Management API Client Secret', secret: true },
      },
    },
    extensibility: { customFieldsSupported: true, extensionHooks: ['MAPPING_TRANSFORM'] },
  },

  // ─── COMMUNICATION CONNECTORS ──────────────────────────────────────
  {
    providerCode: 'SLACK',
    name: 'Slack Enterprise Grid',
    category: 'COMMUNICATION',
    type: 'PARTNER',
    description: 'Real-time alert engine for compliance requirement status changes, trust score updates, and interactive approval notifications.',
    logo: 'Slack',
    version: 'v2.3.1',
    status: 'ACTIVE',
    supportedAuthMethods: ['OAUTH2', 'WEBHOOK_URL'],
    capabilities: ['REALTIME_ALERTING', 'INTERACTIVE_APPROVALS', 'CHANNEL_BROADCAST'],
    supportedResources: ['Channels', 'BotMessages', 'EventSubscriptions'],
    docUrl: 'https://docs.verifychain.io/connectors/slack',
    healthSupport: true,
    webhookSupport: true,
    syncSupport: { enabled: true, modes: ['REAL_TIME'] },
    featureFlags: { autoDiscovery: true, hmacVerification: true },
    configSchema: {
      type: 'object',
      required: ['webhookUrl'],
      properties: {
        webhookUrl: { type: 'string', title: 'Slack Incoming Webhook URL', placeholder: 'https://hooks.slack.com/services/...' },
        defaultChannel: { type: 'string', title: 'Default Alert Channel', default: '#compliance-alerts' },
        apiKey: { type: 'string', title: 'Bot User OAuth Token (Optional)', secret: true },
      },
    },
    extensibility: { customFieldsSupported: false, extensionHooks: ['MESSAGE_FORMATTER'] },
  },
  {
    providerCode: 'MS_TEAMS',
    name: 'Microsoft Teams Workspace',
    category: 'COMMUNICATION',
    type: 'PARTNER',
    description: 'Microsoft Teams webhook and bot connector for operational notifications, compliance alerts, and audit trail cards.',
    logo: 'Teams',
    version: 'v1.9.0',
    status: 'ACTIVE',
    supportedAuthMethods: ['WEBHOOK_URL', 'OAUTH2'],
    capabilities: ['ADAPTIVE_CARDS', 'TEAM_ALERTS', 'COMPLIANCE_BROADCAST'],
    supportedResources: ['Teams', 'Channels', 'AdaptiveCards'],
    docUrl: 'https://docs.verifychain.io/connectors/ms-teams',
    healthSupport: true,
    webhookSupport: true,
    syncSupport: { enabled: true, modes: ['REAL_TIME'] },
    featureFlags: { autoDiscovery: true, hmacVerification: true },
    configSchema: {
      type: 'object',
      required: ['webhookUrl'],
      properties: {
        webhookUrl: { type: 'string', title: 'Teams Connector Webhook URL', placeholder: 'https://outlook.office.com/webhook/...' },
        teamName: { type: 'string', title: 'Team / Channel Name', placeholder: 'VerifyChain Alerts' },
      },
    },
    extensibility: { customFieldsSupported: false, extensionHooks: ['CARD_FORMATTER'] },
  },

  // ─── GENERIC CONNECTORS ───────────────────────────────────────────
  {
    providerCode: 'REST_API',
    name: 'Universal Enterprise REST API',
    category: 'GENERIC',
    type: 'CUSTOM',
    description: 'Generic REST API adapter supporting custom endpoint configurations, OAuth2 / API Key auth, dynamic mapping, and payload validation.',
    logo: 'RestApi',
    version: 'v1.0.0',
    status: 'ACTIVE',
    supportedAuthMethods: ['API_KEY', 'OAUTH2', 'BEARER_TOKEN', 'BASIC_AUTH'],
    capabilities: ['CUSTOM_ENDPOINT_SYNC', 'DYNAMIC_DATA_MAPPING', 'HEADER_INJECTION'],
    supportedResources: ['CustomResources', 'JsonPayloads'],
    docUrl: 'https://docs.verifychain.io/connectors/rest-api',
    healthSupport: true,
    webhookSupport: false,
    syncSupport: { enabled: true, modes: ['FULL', 'INCREMENTAL', 'MANUAL'] },
    featureFlags: { autoDiscovery: false, customMapping: true, rateLimitThrottling: true },
    configSchema: {
      type: 'object',
      required: ['baseUrl'],
      properties: {
        baseUrl: { type: 'string', title: 'Custom REST API Base URL', placeholder: 'https://api.yourcompany.com/v1' },
        authHeaderName: { type: 'string', title: 'Authorization Header Name', default: 'Authorization' },
        apiKey: { type: 'string', title: 'API Key / Token Value', secret: true },
      },
    },
    extensibility: { customFieldsSupported: true, extensionHooks: ['PRE_SYNC', 'POST_SYNC', 'MAPPING_TRANSFORM'] },
  },
  {
    providerCode: 'WEBHOOKS',
    name: 'Enterprise Webhook Gateway',
    category: 'GENERIC',
    type: 'WEBHOOK',
    description: 'Inbound and outbound webhook delivery gateway with HMAC SHA-256 signatures, exponential backoff retries, and delivery logging.',
    logo: 'Webhook',
    version: 'v1.0.0',
    status: 'ACTIVE',
    supportedAuthMethods: ['HMAC_SHA256', 'SECRET_HEADER'],
    capabilities: ['EVENT_STREAMING', 'REALTIME_NOTIFICATIONS', 'HMAC_VERIFICATION', 'RETRY_BACKOFF'],
    supportedResources: ['Events', 'Subscriptions', 'DeliveryLogs'],
    docUrl: 'https://docs.verifychain.io/connectors/webhooks',
    healthSupport: true,
    webhookSupport: true,
    syncSupport: { enabled: true, modes: ['REAL_TIME'] },
    featureFlags: { autoDiscovery: true, hmacVerification: true, retryExponential: true },
    configSchema: {
      type: 'object',
      required: ['targetUrl'],
      properties: {
        targetUrl: { type: 'string', title: 'Webhook Endpoint Target URL', placeholder: 'https://your-server.com/webhooks/verifychain' },
        apiKey: { type: 'string', title: 'HMAC Signing Secret Key', secret: true },
      },
    },
    extensibility: { customFieldsSupported: true, extensionHooks: ['EVENT_TRANSFORM', 'SIGNATURE_CALCULATION'] },
  },

  // ─── GOVERNMENT CONNECTORS ────────────────────────────────────────
  {
    providerCode: 'GSTIN_GOV_PORTAL',
    name: 'GSTN Government Verification Portal',
    category: 'GOVERNMENT',
    type: 'GOVERNMENT',
    description: 'Statutory government portal integration for direct GSTIN taxpayer filing verification, E-Way bill verification, and GSTR compliance audit.',
    logo: 'Gstin',
    version: 'v1.2.0',
    status: 'ACTIVE',
    supportedAuthMethods: ['API_KEY', 'MUTUAL_TLS'],
    capabilities: ['STATUTORY_STATUS_CHECK', 'FILING_AUDIT_SYNC', 'GSTR_MATCHING', 'E_WAY_BILL_AUDIT'],
    supportedResources: ['TaxpayerDetails', 'FilingStatus', 'GstrRecords'],
    docUrl: 'https://docs.verifychain.io/connectors/gst-portal',
    healthSupport: true,
    webhookSupport: false,
    syncSupport: { enabled: true, modes: ['FULL', 'INCREMENTAL'] },
    featureFlags: { autoDiscovery: true, rateLimitThrottling: true },
    configSchema: {
      type: 'object',
      required: ['gstinEnvironment', 'clientId'],
      properties: {
        gstinEnvironment: { type: 'string', title: 'GSTN Portal Environment', default: 'PRODUCTION_API' },
        clientId: { type: 'string', title: 'GSP Client ID', placeholder: 'GSP Client App ID' },
        apiKey: { type: 'string', title: 'GSP Auth Secret Token', secret: true },
      },
    },
    extensibility: { customFieldsSupported: false, extensionHooks: ['FILING_AUDIT'] },
  },
]);

module.exports = {
  BUILTIN_PROVIDERS,
};
